# Phase 1 — Notebook 2: TF-IDF, Category Analysis & NMF

Builds feature matrices and runs all Phase 1 analytical work on the clean
corpus from `01_preprocess.ipynb`. `make_vec`, `add_bin`, and `group_key` —
all imported from `utils.py` — are shared across Steps 1, 3, and 4, which is
the main reason those three live together.

| Step | What | Key output |
|------|------|------------|
| 1 | Build TF-IDF matrices | `features/X_*.npz`, `vocab/vocab_*.csv` |
| 2 | Quality CP2 | `quality/quality_cp2.json` |
| 3 | Category TF-IDF | `analysis/category_tfidf.csv` |
| 4 | NMF topic discovery | `analysis/nmf_topics.csv`, `nmf_weights.csv` |
| 5 | LLM topic labeling | `analysis/llm_topic_labels.json` |

## Setup

In [1]:
import sys, json, os, httpx
from pathlib import Path
from datetime import datetime

import pandas as pd
import numpy as np
import scipy.sparse as sp
from sklearn.decomposition import NMF
from collections import defaultdict

from openai import OpenAI

ROOT = Path(".")
sys.path.insert(0, str(ROOT))
from utils import (load_cfg, tokens_to_str, flat_freq, make_vec,
                   add_bin, group_key, quality_report)

CFG = load_cfg()

def OUT(subdir, fname):
    p = ROOT / "OUTPUTS" / subdir / fname
    p.parent.mkdir(parents=True, exist_ok=True)
    return p

df  = pd.read_parquet(ROOT / "OUTPUTS/prepared/05_filtered.parquet")
ct  = CFG["tfidf"]
print(f"Loaded {len(df):,} projects  |  {df.shape[1]} columns")

Loaded 896,277 projects  |  45 columns

---
## Parameters

All tunable values live here. Edit this cell; do not edit parameter references in downstream cells.

In [2]:
# ── ANALYSIS PARAMETERS — tune here, do not edit downstream cells ────
GROUPBY_FIELD     = CFG["analysis"]["group_by"][0]
GROUP_DESCRIPTION = CFG["analysis"]["group_descriptions"].get(
                        GROUPBY_FIELD,
                        f"groups defined by '{GROUPBY_FIELD}' in DonorsChoose project data")
MIN_SHARED        = 3      # minimum shared NMF terms for cross-group theme detection
MIN_COVERAGE      = CFG["analysis"]["min_coverage"]   # minimum groups a theme must span
N_COMPONENTS      = 8      # NMF topics per group
TOP_N_VOCAB       = 20     # top-N vocab terms fed into NMF per group
N_REPRESENTATIVE  = CFG["llm"]["n_representative_snippets"]

MODEL_LABELING        = "gpt-5.4-mini"   # per-topic labeling loop
MODEL_CURRENT_EVENTS  = "gpt-5.4"        # current events fetch (support step, not full reasoning)
MODEL_SYNTHESIS       = "gpt-5.4"        # cross-topic synthesis call

REVIEW_GROUP      = None   # set to a specific group value to pin; None = auto-selects largest

print(f"GROUPBY_FIELD     = {GROUPBY_FIELD!r}")
print(f"GROUP_DESCRIPTION = {GROUP_DESCRIPTION!r}")

GROUPBY_FIELD     = 'posted_year_quarter'
GROUP_DESCRIPTION = 'quarterly time periods showing how teacher request language has evolved over time on DonorsChoose'

---
## Step 1 — Build TF-IDF Matrices

One vectorizer fit per n-gram range on the full corpus. Trigrams are persisted
even if unused in Phase 1 analysis — Phase 2+ inherits them without re-extraction.

In [3]:
docs  = df["tokens"].apply(tokens_to_str).tolist()
# N-grams are generated here by sklearn rather than in preprocessing.
# The vocab CSVs written below are the persisted n-gram vocabulary the
# spec calls for — just produced at feature time instead of as a
# separate preprocessing step, which avoids a redundant intermediate artifact.
specs = {"X_unigram": (1,1), "X_bigram": (2,2), "X_unigram_bigram": (1,2)}
if CFG["ngrams"]["max_n"] >= 3:
    specs["X_trigram"] = (3, 3)

matrices, vecs = {}, {}
for name, rng in specs.items():
    vec            = make_vec(ct["min_df"], ct["max_df"], rng)
    matrices[name] = vec.fit_transform(docs)
    vecs[name]     = vec
    sz, nnz        = matrices[name].shape, matrices[name].nnz
    print(f"  {name:20s}: shape={sz}  sparsity={1 - nnz/(sz[0]*sz[1]):.3f}")

# Vocab artifact: feature names + IDF weights per matrix
for name, vec in vecs.items():
    (pd.DataFrame({"feature": vec.get_feature_names_out(), "idf": vec.idf_})
       .sort_values("idf")
       .to_csv(OUT("vocab", f"vocab_{name}.csv"), index=False))

feat_dir = ROOT / "OUTPUTS/features"
feat_dir.mkdir(parents=True, exist_ok=True)
for name, X in matrices.items():
    sp.save_npz(feat_dir / f"{name}.npz", X.tocsr())

META_COLS = ["project_id", "project_category", "posted_date", "funded_date",
             "metro_type_at_time_of_posting", "grade_band", "theme_version"]
meta = df[META_COLS].reset_index(drop=True)
try:    meta.to_parquet(feat_dir / "meta.parquet", index=False)
except ImportError: meta.to_csv(feat_dir / "meta.csv", index=False)

assert matrices["X_unigram"].shape[0] == len(df)

  X_unigram           : shape=(896277, 7296)  sparsity=0.991
  X_bigram            : shape=(896277, 739735)  sparsity=1.000
  X_unigram_bigram    : shape=(896277, 747031)  sparsity=1.000
  X_trigram           : shape=(896277, 425983)  sparsity=1.000

---
## Step 2 — Quality Report: Checkpoint 2

In [4]:
qr2 = quality_report(df, label="cp2", matrices=matrices,
                     save_path=OUT("quality", "quality_cp2.json"))

=======================================================  [cp2]
  Projects : 896,277
  Tok/proj : min=5  p50=61  max=197
  Vocab    : 7,297 unique tokens
  X_unigram           : shape=[896277, 7296]  sparsity=0.991
  X_bigram            : shape=[896277, 739735]  sparsity=1.000
  X_unigram_bigram    : shape=[896277, 747031]  sparsity=1.000
  X_trigram           : shape=[896277, 425983]  sparsity=1.000
  Stopwords: FAIL — ['project', 'grade', 'teacher', 'education']
=======================================================

---
## Step 3 — Category TF-IDF

The vectorizer is fit **once** on the full corpus; category slices are scored
by index. This avoids the string-comparison bug (identical token sets across
projects would misclassify rows) and is much faster than refitting per slice.

**Contrast** = token prevalence in this category minus prevalence outside it.

Time bins: defined in `params.yaml` under `analysis.bins`; leave empty for
the full date range.

In [5]:
bins       = CFG["analysis"].get("bins", [])
min_proj   = CFG["analysis"]["min_category_projects"]
top_n      = TOP_N_VOCAB

df_work    = add_bin(df, bins) if bins else df.copy()
df_work    = df_work.reset_index(drop=True)
group_cols = [GROUPBY_FIELD, "bin"] if bins else [GROUPBY_FIELD]

# Fit once; reuse across all slices
all_docs  = df_work["tokens"].apply(tokens_to_str).tolist()
vec_cat   = make_vec(2, 0.95, (1, 2))
X_full    = vec_cat.fit_transform(all_docs)
feat      = vec_cat.get_feature_names_out()
idf_vals  = vec_cat.idf_

def cat_tfidf_slice(idx):
    """Score category slice by index against the rest of the corpus."""
    rest_idx  = df_work.index.difference(idx)
    X_cat     = X_full[idx.tolist()]
    X_rest    = X_full[rest_idx.tolist()]
    cat_prev  = (X_cat  > 0).mean(axis=0).A1
    rest_prev = (X_rest > 0).mean(axis=0).A1 if len(rest_idx) else np.zeros(len(feat))
    tf        = X_cat.mean(axis=0).A1
    return (pd.DataFrame({
                "token":         feat,
                "tf":            tf,
                "idf":           idf_vals,
                "tfidf":         tf * idf_vals,
                "prevalence":    cat_prev,
                "contrast":      cat_prev - rest_prev,
                "project_count": (X_cat > 0).sum(axis=0).A1.astype(int),
            }).nlargest(top_n, "tfidf"))

rows = []
for keys, sub in df_work.groupby(group_cols, observed=True):
    if len(sub) < min_proj: continue
    kd  = group_key(keys, group_cols)
    top = cat_tfidf_slice(sub.index)
    for col, val in kd.items(): top.insert(0, col, val)
    rows.append(top)

if not rows:
    raise RuntimeError(f"No groups met min_proj={min_proj} threshold — lower min_category_projects in params.yaml")
cat_tfidf_df = pd.concat(rows, ignore_index=True)
cat_tfidf_df.to_csv(OUT("analysis", "category_tfidf.csv"), index=False)
print(f"{len(cat_tfidf_df):,} rows  |  {cat_tfidf_df[group_cols[0]].nunique()} groups")
cat_tfidf_df.head(10)

960 rows  |  48 groups

,posted_year_quarter,token,tf,idf,tfidf,prevalence,contrast,project_count
0,2014.0_Q3.0,donation,0.009169,3.421789,0.031376,0.256260,0.170260,3725
1,2014.0_Q3.0,technology,0.009717,2.886265,0.028046,0.327738,0.179005,4764
2,2014.0_Q3.0,ipad,0.006999,3.976284,0.027828,0.170336,0.121322,2476
3,2014.0_Q3.0,common core,0.004331,5.730249,0.024818,0.076087,0.068373,1106
4,2014.0_Q3.0,level,0.008798,2.719247,0.023924,0.315493,0.138539,4586
5,2014.0_Q3.0,able,0.011509,2.060457,0.023714,0.534535,0.191341,7770
6,2014.0_Q3.0,read,0.011291,2.095689,0.023663,0.511282,0.179891,7432
7,2014.0_Q3.0,live,0.008007,2.920210,0.023381,0.272083,0.127577,3955
8,2014.0_Q3.0,reduce lunch,0.005178,4.434582,0.022964,0.113030,0.082124,1643
9,2014.0_Q3.0,improve,0.006974,3.257278,0.022717,0.206384,0.103428,3000

In [6]:
# Top contrast tokens per group — quick cross-group comparison
(cat_tfidf_df.groupby(group_cols[0])
    .apply(lambda g: g.nlargest(5, "contrast")["token"].tolist(), include_groups=False)
    .rename("top_contrast_tokens").to_frame())

                                               top_contrast_tokens
posted_year_quarter
2014.0_Q3.0              [able, read, technology, donation, class]
2014.0_Q4.0              [able, technology, donation, read, class]
2015.0_Q1.0                  [able, donation, class, grade, teach]
2015.0_Q2.0             [able, donation, technology, teach, grade]
2015.0_Q3.0              [able, donation, technology, read, class]
2015.0_Q4.0             [able, donation, technology, class, level]
2016.0_Q1.0             [able, donation, technology, project, one]
2016.0_Q2.0                     [able, donation, free, one, other]
2016.0_Q3.0                         [free, lunch, move, one, able]
2016.0_Q4.0              [free, lunch, technology, class, receive]
2017.0_Q1.0            [free, lunch, technology, receive, poverty]
2017.0_Q2.0                       [free, lunch, receive, low, one]
2017.0_Q3.0             [free, lunch, low, technology, background]
2017.0_Q4.0                    [free, lunch, low, receive, family]
2018.0_Q1.0                [free, lunch, low, receive, technology]
2018.0_Q2.0                        [free, lunch, low, love, teach]
2018.0_Q3.0                        [love, teach, grade, free, one]
2018.0_Q4.0                [class, teach, technology, love, other]
2019.0_Q1.0                       [work, love, teach, other, free]
2019.0_Q2.0                [love, teach, free, opportunity, grade]
2019.0_Q3.0               [love, teach, grade, opportunity, group]
2019.0_Q4.0                      [work, love, teach, class, grade]
2020.0_Q1.0                       [love, teach, read, book, grade]
2020.0_Q2.0             [home, distance, continue, online, family]
2020.0_Q3.0              [home, distance, virtual, covid, teacher]
2020.0_Q4.0            [home, virtual, distance, covid, challenge]
2021.0_Q1.0            [home, virtual, person, distance, pandemic]
2021.0_Q2.0                       [love, home, low, teach, family]
2021.0_Q3.0                 [back, love, pandemic, person, excite]
2021.0_Q4.0                [love, covid, pandemic, eager, diverse]
2022.0_Q1.0                  [covid, pandemic, social, hard, love]
2022.0_Q2.0             [teacher pay, pay, please, library, thank]
2022.0_Q3.0                     [covid, thank, item, seat, supply]
2022.0_Q4.0                   [covid, thank, please, item, supply]
2023.0_Q1.0               [book, library, please, thank, continue]
2023.0_Q2.0                [thank, next, organize, please, pencil]
2023.0_Q3.0                 [covid, item, pandemic, thank, impact]
2023.0_Q4.0             [item, snack, thank, goal project, please]
2024.0_Q1.0                      [foster, thank, snack, item, aim]
2024.0_Q2.0                    [foster, enhance, item, aim, thank]
2024.0_Q3.0            [enhance, foster, item, support, essential]
2024.0_Q4.0           [foster, support, enhance, essential, thank]
2025.0_Q1.0          [support, foster, essential, ensure, enhance]
2025.0_Q2.0               [support, tool, space, essential, build]
2025.0_Q3.0              [support, tool, space, build, confidence]
2025.0_Q4.0             [support, build, confidence, tool, create]
2026.0_Q1.0              [support, confidence, build, focus, feel]
nan_Qnan                                [los, para, las, son, con]

---
## Step 4 — NMF Topic Discovery

NMF is fit independently per category so the dominant axis in one category
does not suppress signal in others. Topics are candidates for human review —
not stable theme definitions (that is Phase 2).

The weights DataFrame records which projects load most strongly on each topic;
Step 5 uses it to select representative snippets by NMF weight rather than
randomly.

In [7]:
cn    = CFG["nmf"]
n_rep = N_REPRESENTATIVE

def nmf_one(docs):
    """Fit NMF on one slice. Returns (topics_df, W) or (None, None)."""
    vec = make_vec(ct["min_df"], ct["max_df"], (1, 2))
    X   = vec.fit_transform(docs)
    if X.shape[1] < N_COMPONENTS: return None, None
    model = NMF(n_components=N_COMPONENTS, random_state=cn["random_seed"],
                init="nndsvd", max_iter=cn["max_iter"])
    W     = model.fit_transform(X)
    vocab = vec.get_feature_names_out()
    rows  = []
    for i, comp in enumerate(model.components_):
        idx = comp.argsort()[::-1][:cn["top_words"]]
        rows.append({"topic_id": i, "top_terms": vocab[idx].tolist(),
                     "top_weights": comp[idx].tolist()})
    return pd.DataFrame(rows), W

all_topics, all_weights = [], []
for keys, sub in df_work.groupby(group_cols, observed=True):
    if len(sub) < min_proj: continue
    kd     = group_key(keys, group_cols)
    docs   = sub["tokens"].apply(tokens_to_str).tolist()
    pids   = sub["project_id"].tolist()
    topics, W = nmf_one(docs)
    if topics is None: continue
    for col, val in kd.items(): topics[col] = val
    all_topics.append(topics)
    for tid in range(W.shape[1]):
        for rank, idx in enumerate(W[:, tid].argsort()[::-1][:n_rep]):
            all_weights.append({**kd, "topic_id": tid, "project_id": pids[idx],
                                "weight": float(W[idx, tid]), "rank": rank})

if not all_topics:
    raise RuntimeError(f"No groups produced NMF topics — check N_COMPONENTS={N_COMPONENTS} vs vocab size, or lower min_category_projects")
topics_df  = pd.concat(all_topics, ignore_index=True)
weights_df = pd.DataFrame(all_weights)
topics_df.to_csv(OUT("analysis", "nmf_topics.csv"),   index=False)
weights_df.to_csv(OUT("analysis", "nmf_weights.csv"), index=False)
print(f"{len(topics_df):,} topics across {topics_df[group_cols[0]].nunique()} groups")
topics_df.head(6)

/opt/miniconda3/lib/python3.13/site-packages/sklearn/decomposition/_nmf.py:1728: ConvergenceWarning: Maximum number of iterations 400 reached. Increase it to improve convergence.
  warnings.warn(
/opt/miniconda3/lib/python3.13/site-packages/sklearn/decomposition/_nmf.py:1728: ConvergenceWarning: Maximum number of iterations 400 reached. Increase it to improve convergence.
  warnings.warn(

384 topics across 48 groups

/opt/miniconda3/lib/python3.13/site-packages/sklearn/decomposition/_nmf.py:1728: ConvergenceWarning: Maximum number of iterations 400 reached. Increase it to improve convergence.
  warnings.warn(

,topic_id,top_terms,top_weights,posted_year_quarter
0,0,"[center, math, fun, kindergarten, letter, acti...","[0.6275405341967571, 0.6079353769842701, 0.576...",2014.0_Q3.0
1,1,"[technology, ipad, computer, access, app, rese...","[0.784373297784523, 0.6047762365213178, 0.5932...",2014.0_Q3.0
2,2,"[supply, room, place, hard, keep, work, feel, ...","[0.32240717563623333, 0.3042318949225226, 0.30...",2014.0_Q3.0
3,3,"[lunch, free, reduce, free reduce, reduce lunc...","[1.044021158089152, 1.0332812241467524, 1.0025...",2014.0_Q3.0
4,4,"[book, reader, read, library, level, interest,...","[0.8080995726394706, 0.7309889092895816, 0.653...",2014.0_Q3.0
5,5,"[science, understand, hand, world, explore, ex...","[0.5113782679110154, 0.3912061306114717, 0.379...",2014.0_Q3.0

In [8]:
_eligible_groups = topics_df[group_cols[0]].unique().tolist()
if REVIEW_GROUP is not None and REVIEW_GROUP not in _eligible_groups:
    raise ValueError(f"REVIEW_GROUP={REVIEW_GROUP!r} not in topics — eligible: {_eligible_groups}")
REVIEW_GROUP = REVIEW_GROUP or topics_df[group_cols[0]].value_counts().index[0]
(topics_df[topics_df[group_cols[0]] == REVIEW_GROUP]
    [["topic_id","top_terms"]]
    .assign(top_terms=lambda x: x.top_terms.apply(lambda t: ", ".join(t[:8]))))

   topic_id                                          top_terms
0         0  center, math, fun, kindergarten, letter, activ...
1         1  technology, ipad, computer, access, app, resea...
2         2   supply, room, place, hard, keep, work, feel, one
3         3  lunch, free, reduce, free reduce, reduce lunch...
4         4  book, reader, read, library, level, interest, ...
5         5  science, understand, hand, world, explore, exp...
6         6  common core, core, common, standard, magazine,...
7         7  special, disability, education, autism, specia...

In [9]:
# Cross-group universal themes — terms appearing in NMF topics across many groups

records = [(r[group_cols[0]], frozenset(r.top_terms)) for _, r in topics_df.iterrows()]

theme_cats = defaultdict(set)
for i, (ci, si) in enumerate(records):
    for cj, sj in records[i+1:]:
        if ci == cj: continue
        shared = si & sj
        if len(shared) >= MIN_SHARED:
            key = frozenset(shared)
            theme_cats[key] |= {ci, cj}

# Sort by n_groups desc, then drop any theme whose terms are a subset of a prior theme
rows = sorted(theme_cats.items(), key=lambda x: -len(x[1]))
seen = []
deduped = []
for terms, cats in rows:
    if len(cats) < MIN_COVERAGE: continue
    if not any(terms <= prior for prior in seen):
        deduped.append({"theme": ", ".join(sorted(terms)[:5]),
                        "n_groups": len(cats),
                        "categories": sorted(cats)})
        seen.append(terms)

pd.DataFrame(deduped).reset_index(drop=True)

,theme,n_groups,categories
0,"book, interest, library, love, read",46,"[2014.0_Q3.0, 2014.0_Q4.0, 2015.0_Q1.0, 2015.0..."
1,"book, interest, level, library, love",39,"[2014.0_Q3.0, 2014.0_Q4.0, 2015.0_Q1.0, 2015.0..."
2,"book, grade, interest, level, library",30,"[2014.0_Q4.0, 2015.0_Q1.0, 2015.0_Q3.0, 2016.0..."
3,"chair, comfortable, desk, flexible, flexible seat",29,"[2017.0_Q2.0, 2017.0_Q3.0, 2017.0_Q4.0, 2018.0..."
4,"income, low, low income",28,"[2014.0_Q4.0, 2016.0_Q2.0, 2016.0_Q3.0, 2017.0..."
...,...,...,...
172,"book, enjoy, grade, interest, level",6,"[2022.0_Q3.0, 2022.0_Q4.0, 2023.0_Q2.0, 2023.0..."
173,"hand, motor, skill",6,"[2022.0_Q3.0, 2022.0_Q4.0, 2023.0_Q2.0, 2023.0..."
174,"fine, motor, play, skill",6,"[2022.0_Q3.0, 2022.0_Q4.0, 2023.0_Q2.0, 2023.0..."
175,"explore, hand, problem, problem solve, skill",6,"[2023.0_Q4.0, 2024.0_Q1.0, 2024.0_Q3.0, 2025.0..."
176,"able, class, one, some, work",6,"[2024.0_Q2.0, 2024.0_Q4.0, 2025.0_Q3.0, 2025.0..."

---
## Step 5 — LLM Topic Labeling

One API call per topic on compressed input only — never raw essay text at scale.
Representative snippets are chosen by NMF weight (not random).

Prompt field limits (`top_unigrams`, `top_bigrams`, `top_nmf_terms`) are applied
as item counts. Parse failures are stored with enough metadata to debug later.

**Requires:** `pip install anthropic` + `ANTHROPIC_API_KEY` env var.
Without the package, stubs are written so downstream steps stay testable.

In [10]:
# Initiate OpenAI credentials

import os
import httpx
from openai import OpenAI

if "client" not in globals():
    from openai import OpenAI
    import httpx
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("Missing OPENAI_API_KEY environment variable.")
    http_client = httpx.Client(verify=False)
    client = OpenAI(api_key=api_key, http_client=http_client)
    print("✅ OpenAI client initialized.")
else:
    print("🔁 Client already loaded; skipping setup.")

✅ OpenAI client initialized.

In [11]:
SYSTEM = (
    "You are an NLP analyst reviewing NMF topic clusters from DonorsChoose teacher "
    "essays. Respond ONLY with a JSON object, no preamble, no markdown fences."
)
PROMPT = (
    f"Group ({GROUPBY_FIELD}): {{group_value}}{{bin_line}}\n"
    "Topic {topic_id}\n"
    "Top unigrams : {unigrams}\n"
    "Top bigrams  : {bigrams}\n"
    "Top NMF terms: {nmf_terms}\n"
    "Representative project tokens:\n"
    "{snippets}\n\n"
    f"Return a JSON object with exactly these keys:\n"
    f"  {GROUPBY_FIELD}, topic_id, proposed_label, description, coherence_flag, notes\n"
    'coherence_flag must be one of: "coherent", "mixed", "redundant"'
)

lc = CFG["llm"]

has_essay = "essay" in df.columns
pid_text  = (df.set_index("project_id")["essay"].str[:300] if has_essay
             else df.set_index("project_id")["tokens"].apply(lambda t: " ".join(t[:40])))

def build_input(t_row):
    terms    = t_row["top_terms"]
    key_cols = [GROUPBY_FIELD] + (["bin"] if "bin" in t_row.index else [])
    mask     = weights_df["topic_id"] == t_row["topic_id"]
    for col in key_cols: mask &= weights_df[col] == t_row[col]
    rep_pids = (weights_df[mask].sort_values("weight", ascending=False)
                    ["project_id"].tolist()[:N_REPRESENTATIVE])
    return {
        "group_value":       t_row[GROUPBY_FIELD],
        "topic_id":  int(t_row["topic_id"]),
        "bin_line":  f"\nBin: {t_row['bin']}"
                     if "bin" in t_row.index and pd.notna(t_row.get("bin")) else "",
        "unigrams":  ", ".join([x for x in terms if " " not in x][:6]),
        "bigrams":   ", ".join([x for x in terms if " " in  x][:4]),
        "nmf_terms": ", ".join(terms[:10]),
        "snippets":  "\n".join(f"- {pid_text.get(p, '')}" for p in rep_pids),
    }

results = []
for _, t in topics_df.iterrows():
    inp  = build_input(t)
    resp = client.chat.completions.create(
        model=MODEL_LABELING,
        messages=[
            {"role": "system", "content": SYSTEM},
            {"role": "user",   "content": PROMPT.format(**inp)},
        ],
    )
    text = resp.choices[0].message.content.strip()
    try:
        obj = json.loads(text)
    except json.JSONDecodeError:
        obj = {"raw": text, "parse_error": True, "model": MODEL_LABELING,
               "model": MODEL_LABELING,
               "timestamp": datetime.now().isoformat(),
               GROUPBY_FIELD: inp["group_value"], "topic_id": inp["topic_id"]}
    results.append(obj)
    print(f"  {inp['group_value']} / topic {inp['topic_id']} "
          f"→ {obj.get('proposed_label', '?')}")

with open(OUT("analysis", "llm_topic_labels.json"), "w") as f:
    json.dump(results, f, indent=2)
print(f"\n{len(results)} labels saved")

  2014.0_Q3.0 / topic 0 → Hands-on literacy and math centers for early learners
  2014.0_Q3.0 / topic 1 → Classroom technology access and digital learning tools
  2014.0_Q3.0 / topic 2 → Classroom space and supply constraints
  2014.0_Q3.0 / topic 3 → Free/Reduced Lunch Eligibility and Low-Income Student Needs
  2014.0_Q3.0 / topic 4 → Reading Access and Student Book Interest
  2014.0_Q3.0 / topic 5 → Science inquiry, problem-solving, and hands-on STEM learning
  2014.0_Q3.0 / topic 6 → Common Core nonfiction and current-events magazines
  2014.0_Q3.0 / topic 7 → Special education and disability support
  2014.0_Q4.0 / topic 0 → Low-income classroom supplies and basic math materials
  2014.0_Q4.0 / topic 1 → Reading materials and comprehension support
  2014.0_Q4.0 / topic 2 → Technology access and classroom devices
  2014.0_Q4.0 / topic 3 → Free/reduced lunch eligibility and low-income student context
  2014.0_Q4.0 / topic 4 → Special education seating and sensory support
  2014.0_Q4.0 / topic 5 → Science exploration and curiosity-driven learning
  2014.0_Q4.0 / topic 6 → Kindergarten literacy and math centers
  2014.0_Q4.0 / topic 7 → School music performance and instrumental ensemble programs
  2015.0_Q1.0 / topic 0 → Music and instruments for low-income students
  2015.0_Q1.0 / topic 1 → Technology-integrated professional development
  2015.0_Q1.0 / topic 2 → Reading, books, and library access
  2015.0_Q1.0 / topic 3 → Free/reduced lunch and low-income student support
  2015.0_Q1.0 / topic 4 → Hands-on math and literacy learning centers for early childhood special education
  2015.0_Q1.0 / topic 5 → Flexible seating and movement supports
  2015.0_Q1.0 / topic 6 → Classroom supplies for writing and creative work
  2015.0_Q1.0 / topic 7 → Hands-on science inquiry and problem solving
  2015.0_Q2.0 / topic 0 → Flexible classroom seating and movement-friendly learning spaces
  2015.0_Q2.0 / topic 1 → Technology Access and Digital Learning Tools
  2015.0_Q2.0 / topic 2 → Free/reduced-price lunch and low-income student need
  2015.0_Q2.0 / topic 3 → Reading, books, and library resources
  2015.0_Q2.0 / topic 4 → Kindergarten literacy skill-building and differentiated practice
  2015.0_Q2.0 / topic 5 → STEM hands-on science problem solving
  2015.0_Q2.0 / topic 6 → Classroom supplies and organizational materials
  2015.0_Q2.0 / topic 7 → Music performance and instrumental education
  2015.0_Q3.0 / topic 0 → Music and performance opportunities
  2015.0_Q3.0 / topic 1 → Flexible seating and movement-friendly classrooms
  2015.0_Q3.0 / topic 2 → Reading engagement and access to books
  2015.0_Q3.0 / topic 3 → Low-income / free-reduced lunch schools
  2015.0_Q3.0 / topic 4 → Access to Technology and Digital Learning Resources
  2015.0_Q3.0 / topic 5 → Classroom basic supplies and organization
  2015.0_Q3.0 / topic 6 → Hands-on STEM science problem solving
  2015.0_Q3.0 / topic 7 → Kindergarten skill practice centers
  2015.0_Q4.0 / topic 0 → Sports, music, and extracurricular enrichment
  2015.0_Q4.0 / topic 1 → Flexible seating and movement-friendly classroom furniture
  2015.0_Q4.0 / topic 2 → Reading books and literacy development
  2015.0_Q4.0 / topic 3 → Free/reduced-price lunch and low-income student need
  2015.0_Q4.0 / topic 4 → Technology access and classroom devices
  2015.0_Q4.0 / topic 5 → Art and classroom supplies
  2015.0_Q4.0 / topic 6 → STEM problem-solving, creativity, and coding
  2015.0_Q4.0 / topic 7 → Special education for students with disabilities and autism
  2016.0_Q1.0 / topic 0 → Sports, music, and team activity equipment
  2016.0_Q1.0 / topic 1 → Flexible seating for focus and movement
  2016.0_Q1.0 / topic 2 → Reading and library literacy resources
  2016.0_Q1.0 / topic 3 → Free/Reduced Lunch and Student Poverty
  2016.0_Q1.0 / topic 4 → Classroom technology access and digital learning tools
  2016.0_Q1.0 / topic 5 → Classroom supplies and basic learning materials
  2016.0_Q1.0 / topic 6 → Hands-on STEM problem solving and maker activities
  2016.0_Q1.0 / topic 7 → Early literacy and foundational skill-building activities for kindergarten/special education
  2016.0_Q2.0 / topic 0 → Reading literacy and access to books
  2016.0_Q2.0 / topic 1 → Flexible seating for active learners
  2016.0_Q2.0 / topic 2 → Free/reduced lunch and high-need student populations
  2016.0_Q2.0 / topic 3 → STEM engineering and maker-based science learning
  2016.0_Q2.0 / topic 4 → Basic classroom supplies and low-income student needs
  2016.0_Q2.0 / topic 5 → Technology access for learning and research
  2016.0_Q2.0 / topic 6 → Hands-on skill practice for special education and early learners
  2016.0_Q2.0 / topic 7 → Low-income, high-challenge classrooms
  2016.0_Q3.0 / topic 0 → Low-income students lacking basic classroom supplies
  2016.0_Q3.0 / topic 1 → Flexible seating and movement options
  2016.0_Q3.0 / topic 2 → Low-income district challenges and student potential
  2016.0_Q3.0 / topic 3 → Free/reduced lunch and breakfast support for economically disadvantaged students
  2016.0_Q3.0 / topic 4 → Healthy active play and physical education
  2016.0_Q3.0 / topic 5 → STEM problem-solving and future technology skills
  2016.0_Q3.0 / topic 6 → Reading books, literacy development, and library access
  2016.0_Q3.0 / topic 7 → Special education and developmental skills support
  2016.0_Q4.0 / topic 0 → Hands-on STEM inquiry and problem-solving
  2016.0_Q4.0 / topic 1 → Flexible seating and movement-friendly classroom options
  2016.0_Q4.0 / topic 2 → Low-income district challenges and student support
  2016.0_Q4.0 / topic 3 → Free/reduced-price lunch and breakfast support
  2016.0_Q4.0 / topic 4 → Reading and literacy access for English learners
  2016.0_Q4.0 / topic 5 → Low-income families facing hardship and needing support
  2016.0_Q4.0 / topic 6 → Technology Access for Learning and Research
  2016.0_Q4.0 / topic 7 → Special education and disability support
  2017.0_Q1.0 / topic 0 → Reading and library resources
  2017.0_Q1.0 / topic 1 → Flexible seating and classroom movement
  2017.0_Q1.0 / topic 2 → Low-income classroom and poverty-related challenges
  2017.0_Q1.0 / topic 3 → Free/reduced-price lunch and food insecurity
  2017.0_Q1.0 / topic 4 → STEM problem-solving and creative exploration
  2017.0_Q1.0 / topic 5 → Technology access and digital learning tools
  2017.0_Q1.0 / topic 6 → Low-income families and students needing basic supplies and support
  2017.0_Q1.0 / topic 7 → Special education and autism support
  2017.0_Q2.0 / topic 0 → STEM problem-solving and technology integration
  2017.0_Q2.0 / topic 1 → Flexible seating options for student comfort and focus
  2017.0_Q2.0 / topic 2 → Low-income student hardship and teacher support
  2017.0_Q2.0 / topic 3 → Free/Reduced Lunch and Food Insecurity Support
  2017.0_Q2.0 / topic 4 → Reading resources and literacy development
  2017.0_Q2.0 / topic 5 → Team sports equipment and participation
  2017.0_Q2.0 / topic 6 → Low-income classroom supplies
  2017.0_Q2.0 / topic 7 → Special education and developmental support
  2017.0_Q3.0 / topic 0 → Reading and literacy support
  2017.0_Q3.0 / topic 1 → Flexible seating and alternative classroom chairs
  2017.0_Q3.0 / topic 2 → Low-income students facing multiple barriers
  2017.0_Q3.0 / topic 3 → Free/reduced lunch and student basic-needs support
  2017.0_Q3.0 / topic 4 → STEM problem-solving and hands-on engineering
  2017.0_Q3.0 / topic 5 → Low-income families, hardship, and classroom support
  2017.0_Q3.0 / topic 6 → Special education early childhood skills and developmental activities
  2017.0_Q3.0 / topic 7 → Technology access and digital learning resources
  2017.0_Q4.0 / topic 0 → STEM problem-solving and coding exploration
  2017.0_Q4.0 / topic 1 → Low-income student needs and barriers
  2017.0_Q4.0 / topic 2 → Flexible seating and movement-friendly classroom options
  2017.0_Q4.0 / topic 3 → Free/Reduced-Price School Meals and Food Insecurity
  2017.0_Q4.0 / topic 4 → Reading access and literacy engagement
  2017.0_Q4.0 / topic 5 → Low-income families and student opportunity constraints
  2017.0_Q4.0 / topic 6 → Technology access and digital learning tools
  2017.0_Q4.0 / topic 7 → Special education and developmental support
  2018.0_Q1.0 / topic 0 → Science, STEM, and problem-solving collaboration
  2018.0_Q1.0 / topic 1 → Low-income, high-need classroom resilience
  2018.0_Q1.0 / topic 2 → Flexible seating and classroom seating options
  2018.0_Q1.0 / topic 3 → Free/Reduced Lunch and Student Poverty
  2018.0_Q1.0 / topic 4 → Low-income family hardship and hurricane displacement
  2018.0_Q1.0 / topic 5 → Bilingual reading and library access for emerging readers
  2018.0_Q1.0 / topic 6 → Classroom technology access for digital learning
  2018.0_Q1.0 / topic 7 → Special education and developmental disabilities support
  2018.0_Q2.0 / topic 0 → Reading access and library books for English learners
  2018.0_Q2.0 / topic 1 → Flexible seating and movement-friendly classroom furniture
  2018.0_Q2.0 / topic 2 → Low-income district challenges and student potential
  2018.0_Q2.0 / topic 3 → Free/reduced-price lunch and student basic-needs support
  2018.0_Q2.0 / topic 4 → Technology, computer access, and STEM problem-solving
  2018.0_Q2.0 / topic 5 → Low-income families struggling to fund classroom and home needs
  2018.0_Q2.0 / topic 6 → Kindergarten hands-on learning activities
  2018.0_Q2.0 / topic 7 → Special education and autism support services
  2018.0_Q3.0 / topic 0 → Basic classroom supplies for low-income and displaced students
  2018.0_Q3.0 / topic 1 → Flexible seating and choice-based classroom furniture
  2018.0_Q3.0 / topic 2 → Free/reduced-price breakfast and lunch support for vulnerable students
  2018.0_Q3.0 / topic 3 → STEM, technology, and maker-based problem solving
  2018.0_Q3.0 / topic 4 → Low-income poverty and student hardship
  2018.0_Q3.0 / topic 5 → Reading books and library access for diverse student interests
  2018.0_Q3.0 / topic 6 → Creative, hands-on problem-solving and growth mindset
  2018.0_Q3.0 / topic 7 → Special education and developmental support
  2018.0_Q4.0 / topic 0 → STEM and technology problem-solving
  2018.0_Q4.0 / topic 1 → Flexible seating and classroom seating options
  2018.0_Q4.0 / topic 2 → Free/reduced lunch and student poverty supports
  2018.0_Q4.0 / topic 3 → Reading access, library books, and literacy interest
  2018.0_Q4.0 / topic 4 → Low-income and poverty-related classroom challenges
  2018.0_Q4.0 / topic 5 → Creative, hands-on project engagement
  2018.0_Q4.0 / topic 6 → Youth sports, teamwork, and low-income family support
  2018.0_Q4.0 / topic 7 → Special education and autism support
  2019.0_Q1.0 / topic 0 → STEM problem-solving and maker technology
  2019.0_Q1.0 / topic 1 → Flexible seating and student choice
  2019.0_Q1.0 / topic 2 → Free/Reduced-Price Lunch and Student Poverty
  2019.0_Q1.0 / topic 3 → Creative, hands-on learning and growth mindset
  2019.0_Q1.0 / topic 4 → Low-income poverty and student hardship
  2019.0_Q1.0 / topic 5 → Reading access and library enrichment
  2019.0_Q1.0 / topic 6 → Community hardship and school sports support
  2019.0_Q1.0 / topic 7 → Special education and developmental support in early childhood
  2019.0_Q2.0 / topic 0 → STEM, coding, and hands-on problem solving
  2019.0_Q2.0 / topic 1 → Flexible seating and classroom choice
  2019.0_Q2.0 / topic 2 → Free/reduced-price lunch and low-income student needs
  2019.0_Q2.0 / topic 3 → Low-income poverty and resource constraints
  2019.0_Q2.0 / topic 4 → Hands-on creative projects and active engagement
  2019.0_Q2.0 / topic 5 → Reading, literacy, and access to books
  2019.0_Q2.0 / topic 6 → Special education and developmental support
  2019.0_Q2.0 / topic 7 → Low-income students lacking supplies and access to extracurricular opportunities
  2019.0_Q3.0 / topic 0 → Low-income family and classroom supply needs
  2019.0_Q3.0 / topic 1 → Flexible seating and movement-friendly classroom choice
  2019.0_Q3.0 / topic 2 → Free/Reduced Lunch and Student Poverty Needs
  2019.0_Q3.0 / topic 3 → Creative, hands-on learning and problem solving
  2019.0_Q3.0 / topic 4 → Reading Culture and Library Access
  2019.0_Q3.0 / topic 5 → Low-income poverty and student hardship
  2019.0_Q3.0 / topic 6 → STEAM problem-solving and hands-on technology learning
  2019.0_Q3.0 / topic 7 → Special education and developmental support
  2019.0_Q4.0 / topic 0 → Low-income family hardship
  2019.0_Q4.0 / topic 1 → Free/reduced-price lunch and low-income school context
  2019.0_Q4.0 / topic 2 → Flexible seating and classroom choice
  2019.0_Q4.0 / topic 3 → Creative, hands-on, growth-oriented learning
  2019.0_Q4.0 / topic 4 → Reading Books, Literacy, and Language Development
  2019.0_Q4.0 / topic 5 → STEM problem-solving and future-ready learning
  2019.0_Q4.0 / topic 6 → Special education and developmental support
  2019.0_Q4.0 / topic 7 → Basic classroom supplies and writing materials
  2020.0_Q1.0 / topic 0 → Low-income student opportunity and resource needs
  2020.0_Q1.0 / topic 1 → Free/reduced-price meal eligibility and student basic needs
  2020.0_Q1.0 / topic 2 → Flexible seating and movement-friendly classroom options
  2020.0_Q1.0 / topic 3 → Reading engagement and access to books
  2020.0_Q1.0 / topic 4 → Hands-on creative engagement and growth mindset
  2020.0_Q1.0 / topic 5 → Low-income poverty and student adversity
  2020.0_Q1.0 / topic 6 → Special education and developmental support
  2020.0_Q1.0 / topic 7 → STEM problem-solving and technology exploration
  2020.0_Q2.0 / topic 0 → Flexible seating / choice-based classroom environment
  2020.0_Q2.0 / topic 1 → Pandemic remote learning and home access challenges
  2020.0_Q2.0 / topic 2 → Free/reduced-price lunch and poverty-related student needs
  2020.0_Q2.0 / topic 3 → Low-income household hardship and access barriers
  2020.0_Q2.0 / topic 4 → Diverse culturally relevant books and reading identity
  2020.0_Q2.0 / topic 5 → Hands-on STEM and foundational skills development
  2020.0_Q2.0 / topic 6 → Remote engagement and participation during COVID closures
  2020.0_Q2.0 / topic 7 → Remote support for multilingual low-income students
  2020.0_Q3.0 / topic 0 → Remote learning and virtual classroom technology
  2020.0_Q3.0 / topic 1 → Hands-on creative engagement and outside-the-box learning
  2020.0_Q3.0 / topic 2 → COVID-safe flexible classroom spaces
  2020.0_Q3.0 / topic 3 → Free/Reduced Lunch and Breakfast Support
  2020.0_Q3.0 / topic 4 → Diverse reading and book access
  2020.0_Q3.0 / topic 5 → Classroom supply materials for early literacy and math
  2020.0_Q3.0 / topic 6 → Special education and autism support
  2020.0_Q3.0 / topic 7 → Low-income household hardship and resilience
  2020.0_Q4.0 / topic 0 → COVID-safe return to in-person learning
  2020.0_Q4.0 / topic 1 → Free/reduced lunch and basic student needs
  2020.0_Q4.0 / topic 2 → Creative, hands-on learning that encourages thinking outside the box
  2020.0_Q4.0 / topic 3 → Diverse Books and Reading Engagement
  2020.0_Q4.0 / topic 4 → Early childhood and special education skill-building activities
  2020.0_Q4.0 / topic 5 → Remote learning technology access
  2020.0_Q4.0 / topic 6 → Low-income English learners and household hardship
  2020.0_Q4.0 / topic 7 → High-poverty, high-need classrooms
  2021.0_Q1.0 / topic 0 → Safe return to in-person learning
  2021.0_Q1.0 / topic 1 → Free/reduced-price lunch and student needs
  2021.0_Q1.0 / topic 2 → Reading, library access, and love of books
  2021.0_Q1.0 / topic 3 → Creative, hands-on learning and thinking outside the box
  2021.0_Q1.0 / topic 4 → Hands-on STEM and skill-building activities
  2021.0_Q1.0 / topic 5 → Virtual/remote learning technology support
  2021.0_Q1.0 / topic 6 → Low-income household hardship
  2021.0_Q1.0 / topic 7 → Early childhood special education and developmental support
  2021.0_Q2.0 / topic 0 → COVID-era supply and remote-learning support needs
  2021.0_Q2.0 / topic 1 → Free/reduced lunch and low-income student support
  2021.0_Q2.0 / topic 2 → Hands-on creative problem-solving and active engagement
  2021.0_Q2.0 / topic 3 → STEM careers, problem-solving, and exploratory science learning
  2021.0_Q2.0 / topic 4 → Early literacy access and fostering a love of reading
  2021.0_Q2.0 / topic 5 → Flexible seating options in the classroom
  2021.0_Q2.0 / topic 6 → Special education, developmental support, and social-emotional skills
  2021.0_Q2.0 / topic 7 → Low-income household poverty challenges
  2021.0_Q3.0 / topic 0 → STEM career exploration and hands-on problem solving
  2021.0_Q3.0 / topic 1 → Creative, hands-on learning and thinking outside the box
  2021.0_Q3.0 / topic 2 → Free/reduced-price lunch and low-income student support
  2021.0_Q3.0 / topic 3 → Flexible seating and student choice
  2021.0_Q3.0 / topic 4 → Reading engagement and accessible books
  2021.0_Q3.0 / topic 5 → Special education and social-emotional development
  2021.0_Q3.0 / topic 6 → COVID-era classroom supplies and safety
  2021.0_Q3.0 / topic 7 → Low-income households and poverty-related challenges
  2021.0_Q4.0 / topic 0 → Low-income family hardship and basic student needs
  2021.0_Q4.0 / topic 1 → Creative, hands-on thinking and problem solving
  2021.0_Q4.0 / topic 2 → Free/reduced lunch and economically disadvantaged students
  2021.0_Q4.0 / topic 3 → Library access and reading engagement
  2021.0_Q4.0 / topic 4 → STEM design and problem-solving projects
  2021.0_Q4.0 / topic 5 → Social-emotional support for special education
  2021.0_Q4.0 / topic 6 → Flexible seating and classroom choice
  2021.0_Q4.0 / topic 7 → Kindergarten literacy and hands-on learning
  2022.0_Q1.0 / topic 0 → Classroom supplies and organization after COVID disruptions
  2022.0_Q1.0 / topic 1 → Free/Reduced Lunch and Low-Income Student Needs
  2022.0_Q1.0 / topic 2 → Flexible seating and classroom choice
  2022.0_Q1.0 / topic 3 → Library books and reading engagement
  2022.0_Q1.0 / topic 4 → Hands-on creative problem solving
  2022.0_Q1.0 / topic 5 → Foundational literacy and math skill practice
  2022.0_Q1.0 / topic 6 → Hands-on STEM exploration and problem solving
  2022.0_Q1.0 / topic 7 → Social-emotional learning and emotional regulation support
  2022.0_Q2.0 / topic 0 → Basic Classroom Supplies and Organization
  2022.0_Q2.0 / topic 1 → Flexible seating and classroom movement
  2022.0_Q2.0 / topic 2 → Independent Reading and Classroom Library Access
  2022.0_Q2.0 / topic 3 → Creative STEM design and hands-on building
  2022.0_Q2.0 / topic 4 → Teacher Pay and Gift Card Resource Support
  2022.0_Q2.0 / topic 5 → Social-Emotional Regulation Space
  2022.0_Q2.0 / topic 6 → Interactive early literacy and math games
  2022.0_Q2.0 / topic 7 → Hard work, low-income family celebration rewards
  2022.0_Q3.0 / topic 0 → Classroom supply organization and basic materials
  2022.0_Q3.0 / topic 1 → Flexible seating and classroom chair options
  2022.0_Q3.0 / topic 2 → Independent Reading Books and Library Access
  2022.0_Q3.0 / topic 3 → Play-Based Foundational Skills and Fine Motor Practice
  2022.0_Q3.0 / topic 4 → Calm corner / social-emotional regulation space
  2022.0_Q3.0 / topic 5 → Teacher pay/gift card for classroom resources
  2022.0_Q3.0 / topic 6 → STEM science-and-engineering creation projects
  2022.0_Q3.0 / topic 7 → Food insecurity and school snack support
  2022.0_Q4.0 / topic 0 → STEM innovation and makerspace learning
  2022.0_Q4.0 / topic 1 → Flexible seating and classroom seating options
  2022.0_Q4.0 / topic 2 → Food insecurity and student incentives
  2022.0_Q4.0 / topic 3 → Independent Reading and Classroom Library Books
  2022.0_Q4.0 / topic 4 → Classroom writing and paper supplies
  2022.0_Q4.0 / topic 5 → Teacher pay gift cards for classroom resources
  2022.0_Q4.0 / topic 6 → Fine motor skill games and hands-on play

In [12]:
labels_df = pd.DataFrame(results)
labels_df.groupby("coherence_flag").size().rename("count").to_frame()
labels_df[[GROUPBY_FIELD,"topic_id","proposed_label","coherence_flag","description"]]

,posted_year_quarter,topic_id,proposed_label,coherence_flag,description
0,2014.0_Q3.0,0,Hands-on literacy and math centers for early l...,coherent,Projects in this cluster describe classroom ce...
1,2014.0_Q3.0,1,Classroom technology access and digital learni...,coherent,Projects focused on providing students with ac...
2,2014.0_Q3.0,2,Classroom space and supply constraints,coherent,"Projects center on limited classroom space, se..."
3,2014.0_Q3.0,3,Free/Reduced Lunch Eligibility and Low-Income ...,coherent,This topic centers on students who qualify for...
4,2014.0_Q3.0,4,Reading Access and Student Book Interest,coherent,Projects centered on helping students find boo...
...,...,...,...,...,...
379,nan_Qnan,3,Hands-on creative problem solving and STEM exp...,coherent,"Projects focused on tactile, creative, hands-o..."
380,nan_Qnan,4,"Comfort, focus, and behavior support",coherent,Projects in this cluster emphasize creating a ...
381,nan_Qnan,5,Early literacy and reading practice,coherent,This topic centers on foundational literacy su...
382,nan_Qnan,6,Social-emotional regulation and sensory support,coherent,Projects in this cluster focus on helping stud...
383,nan_Qnan,7,Engaging Early Literacy and Classroom Activities,coherent,This topic centers on classroom learning exper...

## Current events context for synthesis — fetches once, caches for 7 days

In [13]:
from datetime import timedelta

ce_dir   = OUT("analysis", "placeholder").parent
ce_files = sorted(ce_dir.glob("current_events_*.txt"))
current_events = None

if ce_files:
    newest = ce_files[-1]
    ts_str = newest.stem.replace("current_events_", "")
    try:
        ts = datetime.strptime(ts_str, "%Y%m%d_%H%M%S")
        if datetime.now() - ts < timedelta(days=7):
            current_events = newest.read_text()
            print(f"Using cached current events from {ts.strftime('%Y-%m-%d %H:%M')} → {newest.name}")
    except ValueError:
        pass

if current_events is None:
    print("Fetching current events via web search...")
    ce_resp = client.chat.completions.create(
        model=MODEL_CURRENT_EVENTS,
        messages=[
            {"role": "system", "content": (
                "You are a policy researcher with knowledge of US K-12 education developments "
                "through early 2026. Be specific and factual. Cite named legislation, programs, "
                "or events where possible."
            )},
            {"role": "user", "content": (
                "Summarize recent developments (2025-2026) in these three areas as they relate "
                "to K-12 public schools in the United States: "
                "(1) Food insecurity and economic hardship affecting families with school-age children — "
                "including federal food assistance programs, SNAP, free and reduced lunch policy, "
                "and any broader economic pressures (inflation, unemployment, cost of living) "
                "that may affect whether students come to school fed and ready to learn. "
                "(2) AI tools, devices, and platforms in K-12 classrooms — new products, "
                "district policies, and debates about usage. "
                "(3) Student mental health funding and services — federal or state funding "
                "changes, school counselor ratios, and crisis intervention programs. "
                "Write 3-5 sentences per topic. Be specific, not general."
            )},
        ],
    )
    raw = ce_resp.choices[0].message.content
    current_events = (
        raw if isinstance(raw, str)
        else "\n\n".join(
            (b.get("text", "") if isinstance(b, dict) else getattr(b, "text", ""))
            for b in raw
            if (isinstance(b, dict) and b.get("type") == "text")
            or (hasattr(b, "type") and b.type == "text")
        )
    )
    ts_str  = datetime.now().strftime("%Y%m%d_%H%M%S")
    ce_path = ce_dir / f"current_events_{ts_str}.txt"
    ce_path.write_text(current_events)
    print(f"Saved → {ce_path.name}")

print("\n── Current events context ──────────────────────────────")
print(current_events)

Using cached current events from 2026-03-20 11:33 → current_events_20260320_113311.txt

── Current events context ──────────────────────────────
1) **Food insecurity and economic hardship**
In 2025, food insecurity risk for school-age children remained tied to household finances and federal nutrition policy, especially **SNAP**, **WIC**, and school meal access through the **National School Lunch Program (NSLP)** and **School Breakfast Program (SBP)**. The biggest practical policy issue was not a new school-meal law, but the effect of federal budget fights, state-level **Universal Free School Meals** expansions, and continued use of **Community Eligibility Provision (CEP)** in high-poverty schools to avoid application barriers and reduce stigma. Families also faced persistent pressure from higher housing, food, and childcare costs, so even where headline inflation cooled, many districts reported that students were still arriving hungry because wages and benefits had not kept pace with the cost of living. In several states, lawmakers debated or expanded “**Summer EBT**” / **SUN Bucks** implementation, which matters for K-12 attendance and readiness because food hardship often worsens when schools are closed.

2) **AI tools, devices, and platforms in K-12 classrooms**
By 2025, K-12 systems were moving from ad hoc AI use to more formal district policies covering **generative AI**, student data privacy, plagiarism, and teacher productivity tools. Major education vendors and platforms continued rolling out AI features—such as AI tutoring, lesson generation, translation, and feedback tools—while districts increasingly required human review for anything affecting grades, discipline, or special education decisions. A key debate in 2025 was whether AI should be treated as a classroom aid, a literacy to be taught explicitly, or a surveillance/cheating risk; many districts adopted rules limiting unsanctioned chatbot use on school accounts and devices while piloting approved tools inside **Google Workspace for Education**, **Microsoft Education**, **Canvas**, and similar systems. State education agencies and local boards also focused on compliance with student privacy laws like **FERPA** and on whether AI vendors could retain prompts, student work, or biometric/behavioral data.

3) **Student mental health funding and services**
Federal and state attention to school mental health remained high in 2025–2026, but the central issue was whether pandemic-era and opioid-settlement dollars were being replaced with stable recurring funding. Districts continued to rely on programs created or expanded through the **Bipartisan Safer Communities Act (BSCA)**, **School-Based Mental Health Services Grant Program**, **Mental Health Service Professional Demonstration Grant Program**, and Medicaid billing for school-based services, though many local systems reported grant “cliffs” as temporary money expired. The shortage of school counselors, psychologists, and social workers remained severe; national benchmark guidance from the **American School Counselor Association** still points to a roughly **1:250 counselor-to-student ratio**, and many districts were far above that. Crisis response also remained a major focus, including threat assessment teams, 988 coordination, tele-mental-health referrals, and state crisis intervention initiatives after student suicides, trauma events, and chronic absenteeism linked to depression and anxiety.

In [14]:
# Format topic labels for the prompt — exclude Awaiting Classification
topic_lines = "\n".join(
    f"  {row[GROUPBY_FIELD]} | topic {row.topic_id} | {row.proposed_label}"
    for _, row in labels_df.iterrows()
    if str(row[GROUPBY_FIELD]) != "Awaiting Classification"
)

SYNTHESIS_SYSTEM = (
    "You are a senior program analyst at an educational nonprofit. "
    "You write precise, insight-driven briefings for internal strategy audiences. "
    "You do not pad your answers or state the obvious."
)

SYNTHESIS_PROMPT = f"""
Below is a list of NMF topics discovered from teacher project request essays on DonorsChoose,
grouped by {GROUPBY_FIELD} ({GROUP_DESCRIPTION}).
Each topic represents a cluster of essays with similar language.

{topic_lines}

Your task: identify what is GENUINELY SURPRISING OR DISTINCTIVE in this topic landscape.

Rules:
- Every finding must be grounded in specific topic labels from the list above.
  Do not introduce concepts, themes, or absences that cannot be traced to an actual topic label.
  If you cannot name the specific group and topic label, do not make the finding.
- Skip anything predictable given the group name.
- Skip the free/reduced lunch poverty framing — it appears everywhere and is already known.
- Skip generic engagement/motivation language — it is background noise across all groups.

Focus on:
1. UNEXPECTED CONCENTRATIONS — a topic that appears in a group where it doesn't obviously
   belong. What does it reveal about how teachers are framing requests in that group?
   The test: would a reasonable person be surprised to find this topic in this group?
2. CROSS-GROUP SIGNATURES — a specific program, vendor, pedagogy, or need that shows up
   as a recognizable topic in multiple groups. Name every group it appears in and explain
   why the pattern is meaningful. Look carefully for named programs or institutions.
3. NOTABLE ABSENCES — a topic you would expect given the other topics already present in the
   SAME group, but that is missing. The bar is high: you must be able to point to at least
   two specific topics within that same group that make the gap conspicuous. Do not cite
   topics from other groups as evidence. Do not flag an absence simply because a theme
   exists elsewhere — only flag it if the gap is visible from within the group itself.

Where topics touch on AI tools in the classroom, student hunger or food insecurity, or student
mental health and regulation needs, note this explicitly — but only where the topic genuinely
warrants it. Use the current events context below to add specificity where relevant (for example,
if a topic clusters around food needs, note recent SNAP policy changes; if a topic clusters around
classroom technology, note recent AI-in-schools developments). Do not use current events to 
generate findings, infer unmet need, or introduce themes not already grounded in the discovered 
topic labels.

Format as three labeled sections. Under each, write 2-5 findings as short paragraphs.
Be specific — name the group and topic label every time. Do not use bullet points.

CURRENT EVENTS CONTEXT:
{current_events}
""".strip()

resp = client.chat.completions.create(
    model=MODEL_SYNTHESIS,
    messages=[
        {"role": "system", "content": SYNTHESIS_SYSTEM},
        {"role": "user",   "content": SYNTHESIS_PROMPT},
    ],
)
synthesis = resp.choices[0].message.content.strip()

with open(OUT("analysis", "llm_synthesis.txt"), "w") as f:
    f.write(synthesis)

print(synthesis)

### 1. UNEXPECTED CONCENTRATIONS

In **2015.0_Q1.0 | topic 1 | Technology-integrated professional development**, the distinctive feature is not technology alone but that teacher essays appear to cluster around **professional development** as a fundable classroom need. In this landscape, technology topics are usually framed as student-facing access or devices—compare **2014.0_Q3.0 | topic 1 | Classroom technology access and digital learning tools** and **2015.0_Q2.0 | topic 1 | Technology Access and Digital Learning Tools**. Seeing PD itself become a topic is unusual because it suggests teachers were not just asking for hardware; they were explicitly framing implementation capacity as part of the request.

In **2014.0_Q4.0 | topic 7 | School music performance and instrumental ensemble programs**, the concentration is surprising because the surrounding 2014 topics are dominated by core-academic and need-based framing—reading, science, kindergarten centers, special education seating. A clearly defined **instrumental ensemble** topic that early stands out as a comparatively formal programmatic request, not just general enrichment. The same is true of **2015.0_Q1.0 | topic 0 | Music and instruments for low-income students** and **2015.0_Q2.0 | topic 7 | Music performance and instrumental education**: music is not absent later, but its early prominence as a stable topic is stronger than many would expect from this period’s otherwise basics-heavy request language.

In **2018.0_Q1.0 | topic 4 | Low-income family hardship and hurricane displacement**, the surprise is the specificity of **hurricane displacement** appearing as a standalone topical cluster rather than being absorbed into generic hardship language. That indicates a period where disaster recovery was salient enough to reshape essay language across many requests. It is one of the few topics in the list tied to a concrete external shock rather than a standing classroom condition.

In **2022.0_Q2.0 | topic 4 | Teacher Pay and Gift Card Resource Support**, and then again in **2022.0_Q3.0 | topic 5 | Teacher pay/gift card for classroom resources**, the unusual concentration is a quasi-vendor/payment mechanism topic becoming visible at all. Most topics describe materials or student needs; this one points to teachers structuring requests around **gift cards or teacher-pay marketplace purchases** rather than around the end items themselves. That is a different rhetorical mode—less “we need books” or “we need supplies,” more “we need access to a procurement channel.”

In **2026.0_Q1.0 | topic 1 | Student basic needs support (snacks, hygiene, clothing)**, the striking shift is that teacher requests have moved beyond classroom inputs into a bundled basic-needs frame that explicitly includes **snacks, hygiene, clothing**. This is more expansive than earlier food-only formulations such as **2023.0_Q1.0 | topic 3 | Food insecurity and classroom snacks/lunch support** or **2025.0_Q1.0 | topic 2 | Healthy snacks to reduce hunger and improve focus**. Given the 2025 context around SNAP, CEP, and school meal access, the distinctiveness here is the broadening from meal supplementation to a fuller student-stabilization package.

### 2. CROSS-GROUP SIGNATURES

A clear signature is the rise and persistence of **Teacher Pay / Teachers Pay Teachers-style purchasing language**. It appears in **2022.0_Q2.0 | topic 4 | Teacher Pay and Gift Card Resource Support**, **2022.0_Q3.0 | topic 5 | Teacher pay/gift card for classroom resources**, **2022.0_Q4.0 | topic 5 | Teacher pay gift cards for classroom resources**, **2023.0_Q1.0 | topic 6 | Teacher pay gift cards for classroom resources**, **2023.0_Q2.0 | topic 5 | Teacher Pay Gift Cards for Classroom Resources**, and **2024.0_Q2.0 | topic 6 | Teacher-pay marketplace resources for instruction**. This is meaningful because it is one of the only recurring patterns in the list that points to a recognizable procurement ecosystem rather than a content area. Teachers were not merely requesting resources; they were increasingly naming a marketplace-mediated way of obtaining instructionally ready materials.

Another strong cross-group signature is **flexible seating**, which behaves almost like a permanent request genre. It appears repeatedly from **2015.0_Q1.0 | topic 5 | Flexible seating and movement supports** through **2026.0_Q1.0 | topic 5 | Calm, sensory-friendly self-regulation spaces**? Actually the seating line is cleaner in **2015.0_Q2.0 | topic 0**, **2015.0_Q3.0 | topic 1**, **2015.0_Q4.0 | topic 1**, **2016.0_Q1.0 | topic 1**, **2016.0_Q2.0 | topic 1**, **2016.0_Q3.0 | topic 1**, **2016.0_Q4.0 | topic 1**, **2017.0_Q1.0 | topic 1**, **2017.0_Q2.0 | topic 1**, **2017.0_Q3.0 | topic 1**, **2017.0_Q4.0 | topic 2**, **2018.0_Q1.0 | topic 2**, **2018.0_Q2.0 | topic 1**, **2018.0_Q3.0 | topic 1**, **2018.0_Q4.0 | topic 1**, **2019.0_Q1.0 | topic 1**, **2019.0_Q2.0 | topic 1**, **2019.0_Q3.0 | topic 1**, **2019.0_Q4.0 | topic 2**, **2020.0_Q1.0 | topic 2**, **2020.0_Q2.0 | topic 0**, **2020.0_Q3.0 | topic 2 | COVID-safe flexible classroom spaces**, **2021.0_Q2.0 | topic 5**, **2021.0_Q3.0 | topic 3**, **2021.0_Q4.0 | topic 6**, **2022.0_Q1.0 | topic 2**, **2022.0_Q2.0 | topic 1**, **2022.0_Q3.0 | topic 1**, **2022.0_Q4.0 | topic 1**, **2023.0_Q1.0 | topic 2**, **2023.0_Q2.0 | topic 1**, **2023.0_Q4.0 | topic 3**, **2024.0_Q1.0 | topic 3**, **2024.0_Q2.0 | topic 2**, **2024.0_Q3.0 | topic 2**, **2024.0_Q4.0 | topic 4**, **2025.0_Q1.0 | topic 4**, **2025.0_Q2.0 | topic 3**, **2025.0_Q3.0 | topic 7**, and **2025.0_Q4.0 | topic 7**. The pattern matters because it outlasts multiple shifts in essay language—Common Core, maker/STEM, COVID remote learning, SEL, snacks/basic needs. Flexible seating is not a fad in this corpus; it is a durable infrastructure request that keeps being reinterpreted for focus, choice, comfort, movement, and eventually safety.

A third signature is the migration of **student mental health / regulation language** from special education-adjacent support to generalized classroom infrastructure. Early versions are narrower, like **2014.0_Q4.0 | topic 4 | Special education seating and sensory support** and **2015.0_Q1.0 | topic 5 | Flexible seating and movement supports**. By 2021–2026 it becomes explicit and generalized: **2021.0_Q2.0 | topic 6 | Special education, developmental support, and social-emotional skills**, **2022.0_Q1.0 | topic 7 | Social-emotional learning and emotional regulation support**, **2022.0_Q2.0 | topic 5 | Social-Emotional Regulation Space**, **2022.0_Q3.0 | topic 4 | Calm corner / social-emotional regulation space**, **2022.0_Q4.0 | topic 7 | Social-Emotional Self-Regulation and Calm-Down Supports**, **2023.0_Q1.0 | topic 7 | Social-emotional regulation and safe spaces**, **2023.0_Q2.0 | topic 6 | Calm-down spaces for social-emotional regulation**, **2023.0_Q3.0 | topic Topic 5 | COVID-era social-emotional support and self-regulation**, **2023.0_Q4.0 | topic 0 | Social-emotional regulation and calming supports**, **2024.0_Q1.0 | topic 5 | Social-emotional learning, self-regulation, and sensory supports**, **2024.0_Q2.0 | topic 7 | Social-emotional regulation calm-down spaces**, **2024.0_Q3.0 | topic 4 | Social-Emotional Regulation and Calm Spaces**, **2024.0_Q4.0 | topic 2 | Student emotional regulation and mental health supports**, **2025.0_Q2.0 | topic 5 | Emotional regulation and safe sensory support**, **2025.0_Q3.0 | topic 4 | Calm corners for emotional self-regulation**, **2025.0_Q4.0 | topic 5 | Emotional regulation and calming sensory supports**, and **2026.0_Q1.0 | topic 5 | Calm, sensory-friendly self-regulation spaces**. In current context, this reads less like isolated classroom management and more like teachers absorbing unmet mental-health support functions into material requests as formal service capacity remains thin.

Food-related topics become a distinct late-period signature, and they get more granular over time. The cluster includes **2022.0_Q3.0 | topic 7 | Food insecurity and school snack support**, **2022.0_Q4.0 | topic 2 | Food insecurity and student incentives**, **2023.0_Q1.0 | topic 3 | Food insecurity and classroom snacks/lunch support**, **2023.0_Q2.0 | topic 7 | Student Hunger, Snacks, and Positive Reinforcement**, **2023.0_Q4.0 | topic 2 | Food insecurity and classroom snacks**, **2024.0_Q1.0 | topic 2 | Food insecurity and student hunger**, **2024.0_Q2.0 | topic 5 | classroom snacks and incentive rewards**, **2024.0_Q3.0 | topic 6 | Student hunger, snacks, and food insecurity**, **2024.0_Q4.0 | topic 1 | Food insecurity and classroom snack support**, **2025.0_Q1.0 | topic 2 | Healthy snacks to reduce hunger and improve focus**, **2025.0_Q3.0 | topic 5 | Healthy snacks for focus and energy**, **2025.0_Q4.0 | topic 1 | Healthy snacks as motivation and focus support**, and **2026.0_Q1.0 | topic 1 | Student basic needs support (snacks, hygiene, clothing)**. This is meaningful because the language shifts from abstract poverty markers to immediate in-school provisioning. In light of 2025 debates over SNAP, CEP, and Summer EBT/SUN Bucks, the topic pattern suggests teachers increasingly write requests around day-to-day hunger management inside classrooms rather than relying on administrative eligibility language.

Technology is persistent, but what is notable is that **AI-specific language does not surface as a named topic even in 2025–2026**, despite repeated technology clusters such as **2025.0_Q2.0 | topic 6 | Technology access for instruction and engagement**, **2025.0_Q3.0 | topic 6 | Instructional technology, visual materials, and classroom access tools**, and **2026.0_Q1.0 | topic 6 | Instructional technology and differentiated learning support**. Given 2025’s formalization of AI policy in K-12, the meaningful pattern is that this corpus still codes demand at the level of devices, access, and instructional supports—not generative AI tools, AI tutoring, or AI literacy as standalone request language.

### 3. NOTABLE ABSENCES

In **2020.0_Q2.0**, the conspicuous gap is the absence of a standard classroom technology-access topic despite multiple topics that strongly imply digital dependency: **topic 1 | Pandemic remote learning and home access challenges**, **topic Topic 6 | Remote engagement and participation during COVID closures**, and **topic 7 | Remote support for multilingual low-income students**. This group is clearly organized around remote instruction conditions, yet unlike earlier and later quarters it does not include a straightforward “devices/digital learning tools” topic. That absence suggests the language may have shifted from generic ed-tech aspirations to crisis-specific home-access and participation framing.

In **2022.0_Q2.0**, there is a striking absence of an explicit poverty/meal-eligibility topic even though the quarter includes **topic 4 | Teacher Pay and Gift Card Resource Support** and **topic 7 | Hard work, low-income family celebration rewards**. Within the same group, teachers are explicitly discussing resource substitution and low-income family context, but not through the usual free/reduced lunch shorthand that dominates so many other quarters. The gap matters because it indicates a temporary rhetorical move away from administrative poverty labels and toward direct descriptions of material strain and classroom-level compensation.

In **2023.0_Q1.0**, there is no explicit special education topic even though the group contains **topic 7 | Social-emotional regulation and safe spaces** and **topic 5 | Hands-on STEM play and problem-solving**, both of which often coexist with special education or developmental-support framing elsewhere in the corpus. Here, regulation support appears to have been generalized to the whole classroom rather than attached to a special education identity. That absence is notable because it suggests some needs formerly named through disability categories are being reframed as universal classroom supports.

In **2025.0_Q1.0**, the absence of an explicit technology topic is surprising given **topic 0 | Supportive learning tools and inclusive classroom environment** and **topic 7 | Hands-on problem solving and critical thinking through STEM/STEAM**. In many adjacent quarters, STEM and inclusive-support language is paired with a named technology/access cluster; here it is not. Especially in a 2025 environment when districts were formalizing AI and digital-tool policies, the omission suggests teachers’ request language was centering physical materials, sensory supports, snacks, rewards, and classroom furnishings more than devices or software.

In **2026.0_Q1.0**, there is no explicit flexible seating topic despite **topic 5 | Calm, sensory-friendly self-regulation spaces** and **topic 2 | Classroom Community and Fun Activities**, both of which commonly travel with seating/furniture language elsewhere. Instead, the quarter separates regulation spaces, basic supplies, incentives, and basic-needs supports into their own clusters. The absence suggests that by this point some classroom-comfort needs may have been absorbed into broader regulation and community-building framing rather than appearing as standalone “flexible seating” requests.